Check that we have files when getting line number
Quick fix to prevent an exception that was crashing `yard doc`;
modified {YARD::CodeObjects::Cucumber::LocationHelper#line_number}
to check that there are files before acessing them.

Guessing {#line_number} should not have been getitng called when there
are no files, but not going to take the time now to track it down.

Full trace for any future follow up:

```
NoMethodError: undefined method `last' for nil:NilClass
  ./dev/packages/gems/yard-cucumber/lib/yard/code_objects/cucumber/base.rb:5:in `line_number'
  ./dev/packages/gems/yard-cucumber/lib/yard/code_objects/cucumber/base.rb:13:in `location'
  ./dev/packages/gems/yard-cucumber/lib/templates/default/steptransformers/html/transformers.erb:24:in `block in _erb_cache_62'
  ./dev/packages/gems/yard-cucumber/lib/templates/default/steptransformers/html/transformers.erb:3:in `each'
  ./dev/packages/gems/yard-cucumber/lib/templates/default/steptransformers/html/transformers.erb:3:in `_erb_cache_62'
  ./dev/packages/gems/yard/lib/yard/templates/template.rb:287:in `erb'
  ./dev/packages/gems/yard-cucumber/lib/templates/default/steptransformers/html/setup.rb:29:in `stepdefinitions'
  ./dev/packages/gems/yard/lib/yard/templates/template.rb:367:in `render_section'
  ./dev/packages/gems/yard/lib/yard/templates/template.rb:259:in `block (2 levels) in run'
  ./dev/packages/gems/yard/lib/yard/templates/template.rb:256:in `each'
  ./dev/packages/gems/yard/lib/yard/templates/template.rb:256:in `block in run'
  ./dev/packages/gems/yard/lib/yard/templates/template.rb:398:in `add_options'
  ./dev/packages/gems/yard/lib/yard/templates/template.rb:255:in `run'
  ./dev/packages/gems/yard/lib/yard/templates/template.rb:136:in `run'
  ./dev/packages/gems/yard/lib/yard/templates/template.rb:372:in `render_section'
  ./dev/packages/gems/yard/lib/yard/templates/template.rb:259:in `block (2 levels) in run'
  ./dev/packages/gems/yard/lib/yard/templates/template.rb:256:in `each'
  ./dev/packages/gems/yard/lib/yard/templates/template.rb:256:in `block in run'
  ./dev/packages/gems/yard/lib/yard/templates/template.rb:398:in `add_options'
  ./dev/packages/gems/yard/lib/yard/templates/template.rb:255:in `run'
  ./dev/packages/gems/yard/lib/yard/templates/template.rb:277:in `block in yieldall'
  ./dev/packages/gems/yard/lib/yard/templates/template.rb:412:in `with_section'
  ./dev/packages/gems/yard/lib/yard/templates/template.rb:277:in `yieldall'
  ./dev/packages/gems/yard/templates/default/layout/html/layout.erb:21:in `_erb_cache_7'
  ./dev/packages/gems/yard/lib/yard/templates/template.rb:287:in `erb'
  ./dev/packages/gems/yard-cucumber/lib/templates/default/layout/html/setup.rb:97:in `layout'
  ./dev/packages/gems/yard/lib/yard/templates/template.rb:367:in `render_section'
  ./dev/packages/gems/yard/lib/yard/templates/template.rb:259:in `block (2 levels) in run'
  ./dev/packages/gems/yard/lib/yard/templates/template.rb:256:in `each'
  ./dev/packages/gems/yard/lib/yard/templates/template.rb:256:in `block in run'
  ./dev/packages/gems/yard/lib/yard/templates/template.rb:398:in `add_options'
  ./dev/packages/gems/yard/lib/yard/templates/template.rb:255:in `run'
  ./dev/packages/gems/yard/lib/yard/templates/template.rb:136:in `run'
  ./dev/packages/gems/yard/templates/default/fulldoc/html/setup.rb:35:in `block in serialize'
  ./dev/packages/gems/yard/lib/yard/templates/engine.rb:123:in `block in with_serializer'
  ./dev/packages/gems/yard/lib/yard/logging.rb:82:in `capture'
  ./dev/packages/gems/yard/lib/yard/templates/engine.rb:121:in `with_serializer'
  ./dev/packages/gems/yard/templates/default/fulldoc/html/setup.rb:34:in `serialize'
  ./dev/packages/gems/yard-cucumber/lib/templates/default/fulldoc/html/setup.rb:17:in `init'
  ./dev/packages/gems/yard/lib/yard/templates/template.rb:193:in `initialize'
  ./dev/packages/gems/yard/lib/yard/templates/template.rb:131:in `new'
  ./dev/packages/gems/yard/lib/yard/templates/template.rb:136:in `run'
  ./dev/packages/gems/yard/lib/yard/templates/engine.rb:105:in `generate'
  ./dev/packages/gems/yard/lib/yard/cli/yardoc.rb:355:in `run_generate'
  ./dev/packages/gems/yard/lib/yard/cli/yardoc.rb:267:in `run'
  ./dev/packages/gems/yard/lib/yard/cli/command.rb:14:in `run'
  ./dev/packages/gems/yard/lib/yard/cli/command_parser.rb:72:in `run'
  ./dev/packages/gems/yard/lib/yard/cli/command_parser.rb:54:in `run'
  ./dev/packages/gems/yard/bin/yard:13:in `<top (required)>'
  ./.bundle/ruby/2.3.0/bin/yard:22:in `load'
  ./.bundle/ruby/2.3.0/bin/yard:22:in `<top (required)>'
```